import { classItemSchema, type ClassItem, type ExploreFilter } from '~/schemas/explore'

const wait = (ms = 200) => new Promise((resolve) => setTimeout(resolve, ms))

const classesSeed: ClassItem[] = [
  {
    id: 'morning-reset',
    title: 'Morning Reset',
    startTime: '7:00',
    endTime: '8:00',
    durationMin: 60,
    location: 'Wellness Center A',
    room: 'Room 6',
    dateLabel: 'APR 6',
    trainer: 'Kru Pim',
    trainerExp: '4+ Years Exp',
    trainerQuote:
      "Let's turn your workday stress into graceful energy. Expect a challenge but always with a smile! See you on the mat.",
    trainerAvatar:
      'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage: 'https://www.figma.com/api/mcp/asset/b562c2f4-a42c-4311-af13-9f9bc6c540bf',
    level: 'Beginner',
    slotsLeft: 8,
    status: 'available',
    focus: ['Neck & Shoulders', 'Posture Reset', 'Breathing Flow'],
    category: 'Yoga & Pilates',
  },
  {
    id: 'vinyasa-flow',
    title: 'Vinyasa Flow',
    startTime: '13:00',
    endTime: '14:00',
    durationMin: 60,
    location: 'Wellness Center A',
    room: 'Room 6',
    dateLabel: 'APR 6',
    trainer: 'Kru Pim',
    trainerExp: '4+ Years Exp',
    trainerQuote:
      "Let's turn your workday stress into graceful energy. Expect a challenge but always with a smile! See you on the mat.",
    trainerAvatar: 'https://www.figma.com/api/mcp/asset/000067db-5cb9-4406-af12-b73088bb8a5b',
    trainerFlagEmoji: '🇹🇭',
    heroImage: 'https://www.figma.com/api/mcp/asset/aae988fd-bf16-4055-a1a7-980547787331',
    level: 'Intermediate',
    slotsLeft: 0,
    status: 'full',
    focus: ['Neck & Shoulders', 'Posture Reset', 'Breathing Flow'],
    category: 'Yoga & Pilates',
  },
  {
    id: 'hatha-stretch',
    title: 'Hatha Stretch',
    startTime: '17:00',
    endTime: '17:30',
    durationMin: 30,
    location: 'Wellness Center A',
    room: 'Room 4',
    dateLabel: 'Today',
    trainer: 'Kru Ploy',
    trainerExp: '8+ Years Exp',
    trainerQuote:
      "Let's melt away that desk tension together and recharge your energy for a brilliant afternoon",
    trainerAvatar: 'https://www.figma.com/api/mcp/asset/e37f44e2-f020-4865-81db-e9eb946623f5',
    trainerFlagEmoji: '🇹🇭',
    heroImage: 'https://www.figma.com/api/mcp/asset/55db8103-b327-4626-9665-ec8436e89889',
    level: 'Advanced',
    slotsLeft: 2,
    status: 'available',
    focus: ['Neck & Shoulders', 'Posture Reset', 'Breathing Flow'],
    category: 'Stretching',
  },
  {
    id: 'spinal-flow',
    title: 'Spinal Flow',
    startTime: '20:00',
    endTime: '21:00',
    durationMin: 60,
    location: 'Wellness Center C',
    room: 'Room 2',
    dateLabel: 'Today',
    trainer: 'Kru Beam',
    trainerExp: '5+ Years Exp',
    trainerQuote: 'Gentle flow to reset your spine after a long workday.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1611672585731-fa10603fb9e0?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage: 'https://www.figma.com/api/mcp/asset/d7738760-ce6f-4094-81de-8f0b9f08befd',
    level: 'Beginner',
    slotsLeft: 1,
    status: 'available',
    focus: ['Lower Back', 'Mobility', 'Breathing Flow'],
    category: 'Yoga & Pilates',
  },
  {
    id: 'core-pilates',
    title: 'Core Pilates',
    startTime: '8:30',
    endTime: '9:15',
    durationMin: 45,
    location: 'Wellness Center A',
    room: 'Studio 2',
    dateLabel: 'Today',
    trainer: 'Kru Mint',
    trainerExp: '6+ Years Exp',
    trainerQuote: 'Slow and controlled — your core will thank you tomorrow.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    level: 'Intermediate',
    slotsLeft: 5,
    status: 'available',
    focus: ['Core', 'Posture', 'Stability'],
    category: 'Yoga & Pilates',
  },
  {
    id: 'hiit-blast',
    title: 'HIIT Blast',
    startTime: '12:00',
    endTime: '12:45',
    durationMin: 45,
    location: 'Wellness Center B',
    room: 'Studio 1',
    dateLabel: 'Today',
    trainer: 'Kru Tonnam',
    trainerExp: '7+ Years Exp',
    trainerQuote: 'Quick, intense, effective. Bring water and a towel!',
    trainerAvatar:
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?auto=format&fit=crop&w=600&q=80',
    level: 'Advanced',
    slotsLeft: 3,
    status: 'available',
    focus: ['Cardio', 'Endurance', 'Full Body'],
    category: 'HIIT & Strength',
  },
  {
    id: 'strength-foundations',
    title: 'Strength Foundations',
    startTime: '18:00',
    endTime: '19:00',
    durationMin: 60,
    location: 'Wellness Center B',
    room: 'Strength Room',
    dateLabel: 'Today',
    trainer: 'Kru Boss',
    trainerExp: '9+ Years Exp',
    trainerQuote: 'Build a base that supports everything else you do.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=600&q=80',
    level: 'Beginner',
    slotsLeft: 0,
    status: 'full',
    focus: ['Squat', 'Hinge', 'Push & Pull'],
    category: 'HIIT & Strength',
  },
  {
    id: 'dance-cardio',
    title: 'Dance Cardio',
    startTime: '11:00',
    endTime: '11:45',
    durationMin: 45,
    location: 'Wellness Center A',
    room: 'Studio 3',
    dateLabel: 'Today',
    trainer: 'Kru Nim',
    trainerExp: '5+ Years Exp',
    trainerQuote: 'Forget the mirror, just move and have fun.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1547153760-18fc86324498?auto=format&fit=crop&w=600&q=80',
    level: 'Beginner',
    slotsLeft: 12,
    status: 'available',
    focus: ['Cardio', 'Coordination', 'Mood Boost'],
    category: 'Cardio & Dance',
  },
  {
    id: 'rhythm-ride',
    title: 'Rhythm Ride',
    startTime: '19:00',
    endTime: '19:45',
    durationMin: 45,
    location: 'Wellness Center C',
    room: 'Cycle Room',
    dateLabel: 'Today',
    trainer: 'Kru Aim',
    trainerExp: '6+ Years Exp',
    trainerQuote: 'High energy beats, low impact joints — ride with me.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1530268729831-4b0b9e170218?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80',
    level: 'Intermediate',
    slotsLeft: 4,
    status: 'available',
    focus: ['Cardio', 'Legs', 'Endurance'],
    category: 'Cardio & Dance',
  },
  {
    id: 'deep-stretch',
    title: 'Deep Stretch',
    startTime: '16:00',
    endTime: '16:45',
    durationMin: 45,
    location: 'Wellness Center A',
    room: 'Room 5',
    dateLabel: 'Today',
    trainer: 'Kru Dao',
    trainerExp: '10+ Years Exp',
    trainerQuote: 'Slow down, breathe, and let your body open up.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1599447421416-3414500d18a5?auto=format&fit=crop&w=600&q=80',
    level: 'Beginner',
    slotsLeft: 6,
    status: 'available',
    focus: ['Hips', 'Hamstrings', 'Recovery'],
    category: 'Stretching',
  },
  {
    id: 'mobility-flow',
    title: 'Mobility Flow',
    startTime: '9:30',
    endTime: '10:15',
    durationMin: 45,
    location: 'Wellness Center B',
    room: 'Room 3',
    dateLabel: 'Today',
    trainer: 'Kru Gun',
    trainerExp: '5+ Years Exp',
    trainerQuote: 'Fluid joints, easier life. Lets unstick everything.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1517363898874-737b62a7db91?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1540206395-68808572332f?auto=format&fit=crop&w=600&q=80',
    level: 'Intermediate',
    slotsLeft: 7,
    status: 'available',
    focus: ['Hips', 'Shoulders', 'Spine'],
    category: 'Stretching',
  },
  {
    id: 'evening-yin',
    title: 'Evening Yin',
    startTime: '21:30',
    endTime: '22:15',
    durationMin: 45,
    location: 'Wellness Center A',
    room: 'Room 1',
    dateLabel: 'Today',
    trainer: 'Kru June',
    trainerExp: '7+ Years Exp',
    trainerQuote: 'End your day softly. Long holds, calmer mind.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=80',
    level: 'Beginner',
    slotsLeft: 9,
    status: 'available',
    focus: ['Relaxation', 'Sleep', 'Connective Tissue'],
    category: 'Yoga & Pilates',
  },
  {
    id: 'metcon-mix',
    title: 'MetCon Mix',
    startTime: '6:30',
    endTime: '7:15',
    durationMin: 45,
    location: 'Wellness Center B',
    room: 'Studio 1',
    dateLabel: 'Today',
    trainer: 'Kru Top',
    trainerExp: '8+ Years Exp',
    trainerQuote: 'Wake up the engine. Conditioning + strength in one go.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    level: 'Advanced',
    slotsLeft: 0,
    status: 'full',
    focus: ['Conditioning', 'Strength', 'Power'],
    category: 'HIIT & Strength',
  },
  {
    id: 'kpop-cardio',
    title: 'K-Pop Cardio',
    startTime: '15:00',
    endTime: '15:45',
    durationMin: 45,
    location: 'Wellness Center C',
    room: 'Studio 2',
    dateLabel: 'Today',
    trainer: 'Kru Pang',
    trainerExp: '4+ Years Exp',
    trainerQuote: 'Pop hits, easy choreo, all the sweat.',
    trainerAvatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&h=240&q=80',
    trainerFlagEmoji: '🇹🇭',
    heroImage:
      'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=600&q=80',
    level: 'Beginner',
    slotsLeft: 14,
    status: 'available',
    focus: ['Cardio', 'Coordination', 'Fun'],
    category: 'Cardio & Dance',
  },
]

export async function fetchExploreClasses(filter: ExploreFilter): Promise<ClassItem[]> {
  await wait()
  const data = filter === 'All' ? classesSeed : classesSeed.filter((c) => c.category === filter)
  return data.map((item) => classItemSchema.parse(item))
}

export async function fetchClassById(id: string): Promise<ClassItem> {
  await wait()
  const found = classesSeed.find((c) => c.id === id) ?? classesSeed[0]
  return classItemSchema.parse(found)
}
